spring.application.name=backend-pipefilter

#DataSource (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/resume_analyzer}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:P@rth1102}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Anthropic API
anthropic.api.key=
anthropic.api.url=https://api.anthropic.com/v1/messages

# Server
server.port=8082