package com.layered.backend.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Entity representing the AI evaluation result for a submitted resume.
 * Mapped to the "evaluation_results" table in the database.

 * Each EvaluationResult is linked one-to-one with a {@link Resume},
 * meaning every resume can have at most one evaluation.

 * Lombok annotations:
 *   @NoArgsConstructor  – generates a no-arg constructor (required by JPA)
 *   @AllArgsConstructor – generates a constructor with all fields
 */
@Entity
@Table(name = "evaluation_results")
@NoArgsConstructor
@AllArgsConstructor
public class EvaluationResult {

    /** Primary key, auto-incremented by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Numeric or letter score assigned to the resume after evaluation (e.g. "85" or "B+"). */
    private int score;

    /**
     * Detailed feedback generated by the evaluator explaining the score.
     * Stored as TEXT to accommodate long responses.
     */
    @Column(columnDefinition = "TEXT")
    private String feedback;

    /**
     * Comma-separated or JSON list of keywords found in the resume
     * that matched the job description criteria.
     * Stored as TEXT to support large keyword sets.
     */
    @Column(columnDefinition = "TEXT")
    private String foundKeywords;

    /**
     * Relevant experience or description excerpts extracted from the resume
     * that aligned with the job requirements.
     * Stored as TEXT to support large content.
     */
    @Column(columnDefinition = "TEXT")
    private String missingKeywords;

    /** Timestamp of when the resume analysis was performed. */
    private LocalDateTime analyzedAt;

    /**
     * The resume that was evaluated.
     * Owning side of the one-to-one relationship; the foreign key
     * "resume_id" is stored in this table.
     */
    @OneToOne
    @JoinColumn(name = "resume_id")
    private Resume resume;

    public Long getId() {
        return id;
    }

    public int getScore() {
        return score;
    }

    public String getFeedback() {
        return feedback;
    }

    public String getFoundKeywords() {
        return foundKeywords;
    }

    public String getMissingKeywords() {
        return missingKeywords;
    }

    public LocalDateTime getAnalyzedAt() {
        return analyzedAt;
    }

    public Resume getResume() {
        return resume;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setScore(int score) {
        this.score = score;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    public void setFoundKeywords(String foundKeywords) {
        this.foundKeywords = foundKeywords;
    }

    public void setMissingKeywords(String missingKeywords) {
        this.missingKeywords = missingKeywords;
    }

    public void setAnalyzedAt(LocalDateTime analyzedAt) {
        this.analyzedAt = analyzedAt;
    }

    public void setResume(Resume resume) {
        this.resume = resume;
    }
}
