spring.application.name=backend-layered

#DataSource (PostgreSQL)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/resume_analyzer}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres1}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Anthropic API
anthropic.api.key=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
anthropic.api.url=https://api.anthropic.com/v1/messages

# Server
server.port=8080
